# Generated by Django 2.2.5 on 2019-09-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=100)),
                ('api_secret_key', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=100)),
                ('access_token_secret', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100, unique=True)),
                ('total_tweet', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('twitterid', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('text', models.CharField(max_length=500)),
                ('sentimentscore', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cleaned_text', models.CharField(max_length=500)),
                ('hastags', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddConstraint(
            model_name='twitter',
            constraint=models.UniqueConstraint(fields=('twitterid',), name='new_constraint'),
        ),
    ]
