# Generated by Django 2.2.5 on 2019-09-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchlog',
            name='total_tweet',
            field=models.IntegerField(default=0),
        ),
    ]
