# Generated by Django 2.2.5 on 2019-09-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20190903_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitter',
            name='screenname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
