# Generated by Django 2.2.5 on 2019-09-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_auto_20190903_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchlog',
            name='term',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='searchlog',
            constraint=models.UniqueConstraint(fields=('term',), name='new_constraint'),
        ),
    ]
