# Generated by Django 2.2.5 on 2019-09-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0010_auto_20190903_1705'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='searchlog',
            name='new_constraint',
        ),
        migrations.AddConstraint(
            model_name='searchlog',
            constraint=models.UniqueConstraint(fields=('term',), name='new_constraint1'),
        ),
    ]
