# Generated by Django 2.2.5 on 2019-09-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0013_auto_20190903_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchlog',
            name='term',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
