# Generated by Django 2.2.5 on 2019-09-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0014_auto_20190903_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchlog',
            name='term',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
