# Generated by Django 2.2.5 on 2019-09-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0015_auto_20190903_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchlog',
            name='term',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='cleaned_text',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='hastags',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='screenname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='text',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='twitter',
            name='twitterid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
