# Generated by Django 2.2.5 on 2019-09-03 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0016_auto_20190903_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter',
            name='term',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='twitter.SearchLog'),
            preserve_default=False,
        ),
    ]
