# Generated by Django 2.2.5 on 2019-09-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0017_auto_20190903_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter',
            name='term',
            field=models.CharField(max_length=100),
        ),
    ]
