# Generated by Django 2.2.5 on 2019-09-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0018_auto_20190903_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlog',
            name='term_multiple',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
