# Generated by Django 2.2.5 on 2019-09-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0019_searchlog_term_multiple'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchlog',
            name='term_multiple',
        ),
    ]
